-- BNK School OS V10.10.0
-- Applied migrations:
-- academic_certificate_requests_v10_10_0
-- academic_certificate_photo_access_v10_10_0
-- academic_certificate_preparer_setting_v10_10_0
--
-- Adds:
-- academic_certificate_requests
-- academic_certificate_request_signatures
-- certificate_preparer_user_id / certificate_valid_days
-- RLS + RPC workflow + approve-all + realtime
-- Student photo access for visible certificate requests
